/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface IPaymasterMetadataInterface extends utils.Interface {
  functions: {
    "metadataCID()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "metadataCID"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "metadataCID",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "metadataCID",
    data: BytesLike
  ): Result;

  events: {
    "MetadataUpdate(bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MetadataUpdate"): EventFragment;
}

export interface MetadataUpdateEventObject {
  _cid: string;
}
export type MetadataUpdateEvent = TypedEvent<
  [string],
  MetadataUpdateEventObject
>;

export type MetadataUpdateEventFilter = TypedEventFilter<MetadataUpdateEvent>;

export interface IPaymasterMetadata extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPaymasterMetadataInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    metadataCID(
      overrides?: CallOverrides
    ): Promise<[string] & { _cid: string }>;
  };

  metadataCID(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    metadataCID(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "MetadataUpdate(bytes)"(_cid?: null): MetadataUpdateEventFilter;
    MetadataUpdate(_cid?: null): MetadataUpdateEventFilter;
  };

  estimateGas: {
    metadataCID(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    metadataCID(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
