/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPaymasterMetadata,
  IPaymasterMetadataInterface,
} from "../../../../contracts/account_abstraction/interfaces/IPaymasterMetadata";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes",
        name: "_cid",
        type: "bytes",
      },
    ],
    name: "MetadataUpdate",
    type: "event",
  },
  {
    inputs: [],
    name: "metadataCID",
    outputs: [
      {
        internalType: "bytes",
        name: "_cid",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPaymasterMetadata__factory {
  static readonly abi = _abi;
  static createInterface(): IPaymasterMetadataInterface {
    return new utils.Interface(_abi) as IPaymasterMetadataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPaymasterMetadata {
    return new Contract(address, _abi, signerOrProvider) as IPaymasterMetadata;
  }
}
