/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as sponsorGasPaymaster from "./SponsorGasPaymaster";
export type { sponsorGasPaymaster };
export type { PaymasterApplicationsRegistry } from "./PaymasterApplicationsRegistry";
